blog_module/urls.py
from django.urls import path
from . import views

app_name = 'blog_module'
urlpatterns = [
    path("", views.BlogListView.as_view(), name="blog_list_page"),
    path("<int:category_id>/", views.BlogListView.as_view(), name="blog_list_page"),
#     path('main/category/<int:category_id>/', get_list_by_category, name="category_page"),
#     path('main/author/<int:author_id>/', get_list_by_author, name="author_page"),
    path("detail/<slug:slug>/", views.BlogDetailView.as_view(), name="blog_detail_page"),
    path("submit-comment/", views.submit_comment, name="submit_comment"),
#     path("update/<int:article_id>/", update_page, name="update_page"),
#     path("delete/<int:article_id>/", delete_page, name="delete_page"),
#     path("article/", add_article, name="add_article"),
#     path("person/", add_person, name="add_person"),
    
    # path("update/<int:pk>/", update_page, name="update_page"),
]

eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home_module.urls')),
    path('accounts/', include("account_module.urls")),
    path('blog/', include("blog_module.urls")),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('order/', include('order_module.urls')),
    path('payment/', include('payment_module.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product_module/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ProductView.as_view(), name="products-page"),
    path('product-by-category/<int:cat_id>/', views.ProductView.as_view(), name="products-page"),
    path('old/', views.ProductListView.as_view(), name="products-list-page"),
    path('favorite-product-list/', views.FavoriteProductListView.as_view(), name="favorite_product_list_page"),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name="product-detail"),
    # path('', views.products_view, name="products_page")
]

product_module/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


class ProductCategory(models.Model):
    categories = models.ForeignKey(to="ProductCategory", on_delete=models.CASCADE,
                                   verbose_name=_("categories"), blank=True, null=True)
    title = models.CharField(max_length=200, db_index=True, verbose_name=_("title"))
    url_title = models.CharField(_("url title"), db_index=True, max_length=200)
    is_active = models.BooleanField(_("is active"), default=True)
    is_delete = models.BooleanField(_("is delete"), default=False)

    def __str__(self):
        return f"( {self.url_title} / {self.title} )"

    class Meta:
        db_table = "category"
        verbose_name = _("product category")
        verbose_name_plural = _("product categories")


class Brand(models.Model):
    title = models.CharField(_("brand"), max_length=300)
    is_active = models.BooleanField(_("is active"), default=True)
    
    def __str__(self):
        return self.title
    

class Product(models.Model):
    title = models.CharField(_("title"), max_length=300)
    price = models.IntegerField(_("price"))
    count = models.PositiveIntegerField(default=1, verbose_name=_("count"))
    product_category = models.ManyToManyField(to=ProductCategory, verbose_name=_("product category"),
                                         related_name="product_categories")
    brands = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name="products_brand",
                               verbose_name=_("products brand"), blank=True, null=True)
    short_description = models.CharField(_("short description"), max_length=500, null=True)
    description = models.TextField(_("description"))
    slug = models.SlugField(default='', null=False, unique=True, verbose_name=_("slug"))
    image = models.ImageField(_("image"), upload_to="product/%Y/%m/%d/", blank=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name=_("is active"))
    is_delete = models.BooleanField(_("is delete"), default=False)

    class Meta:
        db_table = "product"
        verbose_name = _("product")
        verbose_name_plural = _("products")
        

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(viewname='product-detail', args=[self.slug])


class ProductTag(models.Model):
    caption = models.CharField(_("caption"), max_length=250, db_index=True)
    product_tags = models.ManyToManyField(Product,
                                          verbose_name=_("product tags"),
                                          related_name="product_tags")

    class Meta:
        db_table = "tag"
        verbose_name = _("product tag")
        verbose_name_plural = _("product tags")

    def __str__(self):
        return self.caption


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product_gallery/")
    
    def __str__(self):
        return f"{self.product.title} {self.image}"
    

product_module/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest
from django.db.models import Avg, Count
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    FormView,
)

from .models import Product, ProductCategory, Brand, ProductGallery
from home_module.models import AdvertisingBanner, MoreVisitedProduct
from tools.ip import get_client_ip_address
from tools.group_list import convert_to_group_list

class FavoriteProductListView(ListView):
    template_name = "product_module/favorite_product_list.html"
    model = Product
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        favorite_products = Product.objects.filter(favorite_product__user=user)
        context["products"] = favorite_products
        return context

"""
def products_list(request):
    all_products = Product.objects.all()
    number_of_products = all_products.count()
    price_average = all_products.aggregate(Avg("price"))
    
    return render(request, "product_module/products-list.html", {
        'products': all_products,
        'number_of_products': number_of_products,
        'price_average': price_average,
    })

class ProductListView(TemplateView):
    template_name = "product_module/products-list.html"
    
    products = Product.objects.all()
    products_count = products.count()
    price_average = products.aggregate(Avg('price'))
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = self.products
        context['number_of_products'] = self.products_count
        context['price_average'] = self.price_average
        return context
"""
class ProductListView(ListView):
    model = Product
    template_name = "product_module/products-list.html"
    context_object_name = 'products'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['price_average'] = Product.objects.aggregate(Avg('price'), Count('title'))
        return context

def product_detail(request: HttpRequest, slug):
    number_of_brands = Brand.objects.annotate(count=Count('products_brand'))
    product = get_object_or_404(Product, slug=slug)
    
    return render(request, "product_module/product-detail.html", {
        'product': product,
        'brands': number_of_brands,
    })
    
class ProductDetailView(DetailView):
    model = Product
    template_name = "product_module/product-detail.html"
    context_object_name = 'product'
    query_pk_and_slug = True
    
    def get_queryset(self):
        is_visited = self.set_visited_product()
        print(f"is visited = {is_visited}")
        return super().get_queryset()
    
    def get_context_data(self, **kwargs):
        loaded_product = self.object
        context = super().get_context_data(**kwargs)
        gallery = list(ProductGallery.objects.filter(product=loaded_product).all())
        gallery.insert(0, loaded_product )
        print(gallery)
        context["gallery"] = convert_to_group_list(gallery, 3)
        return context
    
    
    def set_visited_product(self) -> bool:
        ip = get_client_ip_address(self.request)
        product = Product.objects.filter(slug__iexact=self.kwargs['slug']).first()
        has_ip = MoreVisitedProduct.objects.filter(ip__iexact=ip, product__slug__iexact=product.slug).exists()
        
        if (product is not None) and (ip is not None) and (not has_ip):
            if self.request.user.is_authenticated:
                visited = MoreVisitedProduct(product=product, ip=ip, user=self.request.user)
            else:
                visited = MoreVisitedProduct(product=product, ip=ip)
            visited.save()
            return True 
            
        print(f"user={self.request.user}, ip={ip}, product={product}")
    

"""_summary_
def products_view(request):
    products = Product.objects.all()
    number_of_brands = Brand.objects.annotate(count=Count('products_brand'))
    return render(request, "product_module/products-page.html", {
        'products': products,
        'brands': number_of_brands,
    })"""
    

class ProductView(ListView):
    template_name = "product_module/products-page.html"
    model = Product
    context_object_name = 'products'
    paginate_by = 3
    
    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context['start_price'] = 5
    #     context['end_price'] = 1000000
    #     print('context')
    #     return context
    
    def get_queryset(self, *args, **kwargs):
        query = super().get_queryset()
        category_id = self.kwargs.get('cat_id')
        print(self.kwargs, self.request.GET)
        query = query.filter(is_active=True, is_delete=False)
        if category_id:
            query = query.filter(product_category__id=category_id)
        
        order_query_by_price = query.order_by('price')    
        min_price = 0
        max_price = order_query_by_price.last().price or 900000000  
        start_price = self.request.GET.get('start_price') or min_price
        end_price = self.request.GET.get('end_price') or max_price
        query = query.filter(price__gte=start_price)
        query = query.filter(price__lte=end_price)

        return query
    
            
def sidebar_loader(request:HttpRequest, *args, **kwargs):
    brands_with_count = Brand.objects.annotate(count=Count('products_brand'))
    categories_with_count = ProductCategory.objects.annotate(count=Count('categories'))
    
    order_query_by_price = Product.objects.order_by('price')
    min_price = 0
    max_price = order_query_by_price.last().price or 900000000
    start_price = request.GET.get('start_price') or min_price
    end_price = request.GET.get('end_price') or max_price
    
    banners = AdvertisingBanner.objects.filter(location__iexact="products-list-page")
    
    return render(request=request, template_name="includes/left-sidebar.html", context={
        'brands': brands_with_count,
        'list_category': categories_with_count,
        'start_price': start_price,
        'end_price': end_price,
        'max_price': max_price,
        'step': 1000000,
        'banners': banners,
    })

product_module/templates/includes/left-sidebar.html
{% load static %}
{% load poll_extras %}
{% load thumbnail %}
<div class="left-sidebar">
    <h2>دسته بندی محصولات</h2>
    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
    
        <div class="panel panel-default">
            {% for category in list_category %}
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordian" href="#{{category.id}}">
                            {% if not category.categories %}
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                {{ category.title }} 
                            {% endif %}
                        </a>
                    </h4>
                </div>
                <div id="{{category.id}}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            {% for prod in  category.productcategory_set.all %}
                                <li><a href="{% url "products-page" cat_id=prod.id %}">{{ prod }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% for product in products %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a href="#">{{product.title}}</a></h4>
            </div>
        </div>
        {% empty %}EMPTY{% endfor %}
    </div><!--/category-productsr-->

    <div class="brands_products"><!--brands_products-->
        <h2>برنـدها</h2>
        <div class="brands-name">
            <ul class="nav nav-pills nav-stacked">
                {% for brand in brands %}
                    <li><a href=""> <span class="pull-left">({{brand.count}})</span>{{ brand }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div><!--/brands_products-->
    
    <div class="price-range"><!--price-range-->
        <h2>فیلتـر قیمـت</h2>
        <div class="well">
                <input type="text"
                    class="span2"
                    value="{{start_price}},{{end_price}}"
                    data-slider-min="0"
                    data-slider-max="{{ max_price }}"
                    data-slider-step="{{step}}"
                    data-slider-value="[{{ start_price }},{{ end_price }}]"
                    id="sl2" >
                <br>
                <b>0</b> <b class="pull-left">{{ max_price }} </b>
            </div>
        </div><!--/price-range-->
        <div>
            <form action="" method="get" id="filter_form">
                <input type="hidden" name="page" id="page" value="{{page_obj.number}}">
                <input type="hidden" name="start_price" id="start_price" value="{{start_price}}">
                <input type="hidden" name="end_price" id="end_price" value="{{end_price}}">
            </form>
            <button class="btn btn-success btn-block" onclick="filterPriceButton()">فیلتر</button>
        </div>
    
    <div class="shipping text-center"><!--shipping-->
        {% for banner in banners %}
            {% thumbnail banner.image "270x550" as im %}
                <a href="{{banner.url}}" target="_blank"><img src="{{im.url}}" alt=""></a>
                <br><br>
            {% endthumbnail %}
        {% endfor %}
    </div><!--/shipping-->
    
</div>

product_module/templates/includes/product-item-partial.html
{% load static %}
{% load poll_extras %}

<div class="col-sm-4">
    <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center">
                <img src="
                {% if product.image %}{{product.image.url}}{% else %}{% static "images/shop/product.jpg" %}
                {% endif %}" alt="{{product.title}}">
                <h2>{{ product.price | dwc}} </h2>
                <p>{{ product.title }}</p>
                <input type="hidden" name="count_of_product" value="1">
                <a onclick="addToProductOrderList({{product.id}})" class=" cursor_pointer btn btn-default add-to-cart">
                    <i class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</a>
            </div>
            <div class="product-overlay">
                <div class="overlay-content">
                    <h2>{{ product.price|dwc }} </h2>
                    <p> {{ product.title }} </p>
                    <a onclick="addToProductOrderList({{product.id}})" class=" cursor_pointer btn btn-default add-to-cart">
                        <i class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</a>
                </div>
            </div>
        </div>
        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href="{{ product.get_absolute_url }}"><i class="fa fa-plus-square"></i>جزئیات</a></li>
                {% if position == "delete_from_favorite_list" %}
                <li class="cursor_pointer">
                    <a onclick="delete_from_favorite_list({{product.id}},{{request.user.id}})" ><i class="fa fa-plus-circle"></i>حذف</a>
                </li>
                {% else %}
                <li>
                    <a href=""><i class="fa fa-plus-square"></i>مقایسه</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>