account_module/urls.py
from django.urls import path
from . import views


app_name = "account_module"
urlpatterns = [
    path('user-panel-dashboard/', views.UserPanelDashboardView.as_view(), name="user_panel_dashboard_page"),
    path('edit-user-profile/', views.EditUserProfileView.as_view(), name="edit_user_profile_page"),
    path('register/', views.RegisterView.as_view(), name="register_page"),
    path('active-account/<str:active_code>/', views.ActiveAccountView.as_view(), name="active_account_page"),
    path('login/', views.LoginView.as_view(), name="login_page"),
    path('logout/', views.LogoutView.as_view(), name="logout_page"),
    path('forget-pass/', views.ForgetPasswordView.as_view(), name="forget_pass_page"),
    path('change-pass/', views.ChangePasswordView.as_view(), name="change_pass_page"),
    path('reset-pass/<str:pass_ok>/', views.ResetPasswordView.as_view(), name="reset_pass_page"),
]

blog_module/urls.py
from django.urls import path
from . import views

app_name = 'blog_module'
urlpatterns = [
    path("", views.BlogListView.as_view(), name="blog_list_page"),
    path("<int:category_id>/", views.BlogListView.as_view(), name="blog_list_page"),
#     path('main/category/<int:category_id>/', get_list_by_category, name="category_page"),
#     path('main/author/<int:author_id>/', get_list_by_author, name="author_page"),
    path("detail/<slug:slug>/", views.BlogDetailView.as_view(), name="blog_detail_page"),
    path("submit-comment/", views.submit_comment, name="submit_comment"),
#     path("update/<int:article_id>/", update_page, name="update_page"),
#     path("delete/<int:article_id>/", delete_page, name="delete_page"),
#     path("article/", add_article, name="add_article"),
#     path("person/", add_person, name="add_person"),
    
    # path("update/<int:pk>/", update_page, name="update_page"),
]

eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home_module.urls')),
    path('accounts/', include("account_module.urls")),
    path('blog/', include("blog_module.urls")),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('order/', include('order_module.urls')),
    path('payment/', include('payment_module.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_module/models.py
from random import randint
from django.contrib.auth import get_user_model
from django.db import models, transaction
from django.utils.text import slugify
from django_extensions.db.fields import AutoSlugField
from model_utils import Choices
from model_utils.fields import StatusField   
from django.urls import reverse


User = get_user_model()

class Category(models.Model):
    parent = models.ForeignKey("self", blank=True, null=True,
                                     verbose_name="والد", on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    is_active = models.BooleanField(default=True)
    created_time = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, allow_unicode=True, db_index=True)
    
    def __str__(self):
        return self.title
    
    @transaction.atomic
    def save(self, *args, **kwargs):
        main_slug = slugify(self.title, allow_unicode=True).lower()
        while Category.objects.filter(slug=main_slug).exists():
            rand_int = randint(101, 1000)
            main_slug = f"{main_slug}-{rand_int}"
        self.slug = main_slug
        super().save(*args, **kwargs)
    
class Article(models.Model):
    STATUS = Choices('draft', 'published', 'hidden', 'archived', 'deleted')
    status = StatusField(choices=STATUS, default='draft', editable=True)
    
    categories = models.ManyToManyField(to='Category')
    title = models.CharField(max_length=250)
    short_description = models.CharField(max_length=500)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    is_show = models.BooleanField(default=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/article/%Y/%m/')
    slug = AutoSlugField(populate_from=['title', 'author'], unique=True, allow_unicode=True, db_index=True)
    
    class Meta:
        index_together = [['slug', 'created_time']]
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(viewname='blog_module:blog_detail_page', args=(self.slug,))

class Comment(models.Model):
    STATUS = Choices('draft', 'published', 'hidden', 'archived', 'deleted')
    status = StatusField(choices=STATUS, default='published')
    # status = models.CharField(choices=STATUS, max_length=10, default='published')
    parent = models.ForeignKey("self", blank=True, null=True,
                               on_delete=models.CASCADE, related_name='replies')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_comments')
    title = models.CharField(max_length=250)
    created_time = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    
    def __str__(self):
        return f"comment by {self.author} => {self.title}"
    

blog_module/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Avg, Count
from django.contrib.auth import get_user_model

from . import models
from . import forms
from home_module.models import AdvertisingBanner

User = get_user_model()
article_selected_id = 0


class BlogListView(generic.ListView):
    model = models.Article
    template_name = "blog_module/index.html"
    context_object_name = 'articles'
    queryset = model.objects.filter(is_show=True)
    paginate_by = 1
    
    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)

        context["categories"] = models.Category.objects.filter(is_active=True, parent=None)
        
        context['banners'] = AdvertisingBanner.objects.filter(location__iexact="blog_list_page")
        
        return context
    
    def get_queryset(self):
        query =  super().get_queryset()
        category_id = self.kwargs.get('category_id')
        if category_id:
            query = query.filter(categories__id=category_id, is_show=True)
        return query

    
class BlogDetailView(generic.DetailView):
    model = models.Article
    template_name = "blog_module/detail.html"
    template_name_field = 'article'
    
    def get_context_data(self, *args, **kwargs) -> dict:
        context = super().get_context_data(*args, **kwargs)
        article = kwargs.get('object')
        context["comments"] = models.Comment.objects.filter(article=article.id, status='published',
                                                            parent=None).order_by('-created_time').prefetch_related('replies')
        context['comments_count'] = models.Comment.objects.filter(status='published',
                                                            article=article.id).count()
        # avatar = models.Comment.objects.filter(author__userprofile__avatar__isnull=False)
        # print(context, self.kwargs, avatar)
        return context
    
def submit_comment(request:HttpRequest):
    print(request.GET)
    if request.user.is_authenticated:
        comment = request.GET.get('comment')
        article_selected_id = request.GET.get('article_id')
        article = get_object_or_404(models.Article, id=article_selected_id)
        parent_id = request.GET.get('parent_id')
        if parent_id.isdigit():
            parent = get_object_or_404(models.Comment, id=parent_id)
        else:
            parent = None
        author = request.user
        models.Comment.objects.create(body=comment, author=author, article=article, parent=parent)
        context = {
            'comments' : models.Comment.objects.filter(article=article_selected_id, status='published',
                                                        parent=None).order_by('-created_time').prefetch_related('replies'),
            'comments_count' : models.Comment.objects.filter(status='published',
                                                        article=article_selected_id).count()
        }
        return render(request, "blog_module/includes/inbox-reload-comment.html", context)
    
    # if request.user.is_authenticated:
    #     if request.method == 'POST' and request.headers.get('X-Requested-With') == 'AjaxRequest':
    #         message = request.POST.get('message')
    #         print(message)
    #         author = request.user
    #         article_selected_id = request.POST.get('article_id')
    #         article = get_object_or_404(models.Article, id=article_selected_id)
    #         comment = models.Comment.objects.create(
    #             body=message, author=author, article=article, title='test title')
    #         return JsonResponse({"success": True, "message": "نظر شما با موفقیت ثبت شد."})
    #     return JsonResponse({"success": False, "message": "خطا در ارسال نظر."})


def blog_page(request):
    article = Article.objects.all()
    authors = User.objects.all()
    categories = Category.objects.all()
    count_of_category = Category.objects.annotate(Count('article'))
    count_of_article_per_author = User.objects.annotate(Count('article'))
    # a=Article.categories.field_name
    # print(count_of_article_per_author)
    # print(a)
    # print('++++++')
    search_key = request.GET.get("search_title")
    # print(request.GET.get('search_text'), 11)
    if search_key:
        article = article.filter(title__icontains=search_key)
        
    paginator = Paginator(article, 6)
    num_page = request.GET.get('page')
    page_obj = paginator.get_page(num_page)

    context = {
        'articles': page_obj,
        'authors': authors,
        's_key': search_key,
        'categories': categories,
        'count_of_category': count_of_category,
        'count_of_article_per_author': count_of_article_per_author,
    }
    return render(request, "blog/index.html", context)

def detail_page(request, article_id):
    if request.method == 'post':
        article_selected_id = request.POST.id
        
    a = get_object_or_404(Article, id=article_id)
    article_selected_id = article_id
    context = {
        'article': a,
    }
    return render(request, "blog/details.html", context)

@login_required
def add_article(request):
    if request.user.is_authenticated:
        # print(request.method)
        if request.method == 'GET':
            form = CreateArticle()
        else:
            form = CreateArticle(data=request.POST, files=request.FILES)
            print(f"is valid: {form.is_valid()}")
            if form.is_valid():
                # print(form.cleaned_data)
                article_title = form.cleaned_data.get('title')
                article_text = form.cleaned_data['text']
                article_created_date = form.cleaned_data['created_date']
                article_is_show = form.cleaned_data['is_show']
                article_image = form.cleaned_data['image']
                # article_author = form.cleaned_data['author']
                # item = Person.objects.get(pk=article_author)
                Article.objects.create(title=article_title,
                                       text=article_text, created_date=article_created_date,                                   is_show=article_is_show,
                                       image=article_image,
                                       author=request.user
                                    )
                a = Article.objects.last().pk
                # print(f"last item is: {a}")
                return redirect('blog:detail_page', a)

        context = {
            'form': form,
        }
        return render(request, "blog/add_article.html", context)
    else:
        return redirect('accounts:login_page')

@login_required
def add_person(request):
    if request.method == 'GET':
        # print(request.method)
        form_add = AddPerson()
    else:
        # print(request.method)
        form_add = AddPerson(data=request.POST)
        if form_add.is_valid():
            # print(f"is valid: {form_add.is_valid()}")
            # print(form_add.cleaned_data)
            person_fname = form_add.cleaned_data.get('first_name')
            person_lname = form_add.cleaned_data.get('last_name')
            person_age = form_add.cleaned_data.get('age')
            person_email = form_add.cleaned_data.get('email')
            P = Person.objects.create(
                first_name=person_fname,
                last_name=person_lname,
                age=person_age,
                email=person_email
            )
            return redirect("blog:blog_page")

    return render(request, "blog/add_person.html", {'form': form_add})

@login_required
def update_page(request, article_id):
    record = get_object_or_404(Article, id=article_id)
    # print(request.user.id)
    # print(record.author.id)
    if request.user.id != record.author.id:
        return HttpResponse(f"page error.../{request.user}/{record.author}")
    if request.method == 'GET':
        # print(record)
        article_form = UpdateArticle(initial={
            'title' : record.title,
            'text' : record.text,
            'created_date' : record.created_date,
            'is_show' : record.is_show,
            # 'imag' : record.image,
            })
    else:
        article_form = UpdateArticle(data=request.POST, files=request.FILES)
        if article_form.is_valid():
            title = article_form.cleaned_data.get('title')
            text = article_form.cleaned_data.get('text')
            # created_date = article_form.cleaned_data.get('created_date')
            is_show = article_form.cleaned_data.get('is_show')
            image = article_form.cleaned_data.get('image')
            
            record.title = title
            record.text = text
            # record.crated_date = created_date
            record.is_show = is_show
            if image:
                record.image = image
            
            record.save()
            
            return redirect('blog:detail_page', article_id)
    context = {'form' : article_form, 'edit' : record}
            
    return render(request, 'blog/edit_article.html', context)

@login_required
def delete_page(request, article_id):
    record = get_object_or_404(Article, pk=article_id)
    if request.user.id != record.author.id:
        return HttpResponse("page error...")
    record.delete()
    return redirect('blog:blog_page')

def get_list_by_category(request, category_id):
    articles = Article.objects.filter(categories=category_id)
    categories = Category.objects.all()
    count_of_category = Category.objects.annotate(Count('article'))
    
    paginator = Paginator(object_list=articles, per_page=3)
    num_page = request.GET.get('page')
    page_obj = paginator.get_page(number=num_page)
    
    context = {

blog_module/templates/blog_module/add_article.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Created Form{% endblock title %}
{% block content %}
<div class="d-block text-bg-secondary text-end container ">
    <form action="{% url "blog:add_article" %}" method="post" class="m-1 p-3" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <div class="input-form a-title">
            <label for="{{ form.title.id_for_label}}" class="form-label">{{ form.title.label}}</label>
            {{ form.title }}
            {% for error in form.title.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-text">
            <label for="{{ form.text.id_for_label}}" class="form-label">{{ form.text.label}}</label>
            {{ form.text }}
            {% for error in form.text.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-date">
            <label for="id_created_date" class="form-label">تاریخ</label>
            {{ form.created_date }}
            {% for error in form.created_date.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-checkbox">
            <label for="id_is_show" class="form-label">نمایش داده شود؟</label>
            {{ form.is_show }}
            {% for error in form.is_show.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-imag">
            <label for="id_image" class="form-label">عکس مقاله</label>
            {{ form.image }}
            {% for error in form.image.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-author">
            <label for="id_author" class="form-label"> نویسنده</label>
            {{ form.author }}
            {% for error in form.author.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        {% comment %} {{form.errors}} {% endcomment %}
        <input type="submit" value="submit" class="btn bg-transparent border-primary border-3 hover d-block m-auto w-25">
    </form>
</div>
{% endblock content %}

blog_module/templates/blog_module/add_person.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Add Person{% endblock title %}
{% block content %}
    <div width="100%" class="bg-dark p-5">
        <div class="container text-bg-secondary mt-5">
            <form action="{% url "blog:add_person" %}" method="post" class="m-1 p-3">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="submit" class="btn bg-transparent border-primary border-3 hover d-block m-auto w-25 mt-5">
            </form>
        </div>
    </div>
{% endblock content %}

blog_module/templates/blog_module/edit_article.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Created Form{% endblock title %}
{% block content %}
<div class="d-block text-bg-secondary text-end container ">
    <form action="" method="post" class="m-1 p-3" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <div class="input-form a-title">
            <label for="{{ form.title.id_for_label}}" class="form-label">{{ form.title.label}}</label>
            {{ form.title }}
            {% for error in form.title.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-text">
            <label for="{{ form.text.id_for_label}}" class="form-label">{{ form.title.label}}</label>
            {{ form.text }}
            {% for error in form.text.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="row mb-3">
            <div class="col">
                {% comment %} <div class="input-form a-date">
                    <label for="id_created_date" class="form-label">تاریخ</label>
                    {{ form.created_date }}
                    {% for error in form.created_date.errors %}
                        <smal class="text-warning fs-6">{{ error }}</smal>
                    {% endfor %}
                </div> {% endcomment %}
                <div class="input-form a-checkbox">
                    <label for="id_is_show" class="form-label">نمایش داده شود؟</label>
                    {{ form.is_show }}
                    {% for error in form.is_show.errors %}
                        <smal class="text-warning fs-6">{{ error }}</smal>
                    {% endfor %}
                </div>
            
                <div class="input-form a-imag col">
                    <label for="id_image" class="form-label"><a href="{{edit.image.url}}">عکس مقاله</a></label>
                    {{ form.image }}
                    {% for error in form.image.errors %}
                        <smal class="text-warning fs-6">{{ error }}</smal>
                    {% endfor %}
                </div>
            </div>
            <div class="col justify-content-center d-flex" >
                <img class="w-50" alt="{{ edit.image }}" src="{{ edit.image.url }}">
                {% for error in form.author.errors %}
                    <smal class="text-warning fs-6">{{ error }}</smal>
                {% endfor %}
            </div>
        </div>
        {% comment %} {{form.errors}} {% endcomment %}
        <input type="submit" value="Update" class="btn bg-transparent border-primary border-3 hover d-block m-auto w-25">
    </form>
</div>
{% endblock content %}

blog_module/templates/blog_module/index.html
{% extends "shared/_layout.html" %}
{% load static %}
{% load thumbnail %}
{% load jalali_tags %}
{% block title %}لیست مقالات{% endblock title %}

{% block content %}
    <section>
		<div class="container">
			<div class="row">
				
				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">آخریـن مقالات</h2>
                        {% for article in articles %}
                            <div class="single-blog-post">
                                <h3>{{article.title}}</h3>
                                <div class="post-meta">
                                    <ul>
                                        <li><i class="fa fa-user"></i>{{article.author}}</li>
                                        <li><i class="fa fa-clock-o"></i>{{article.created_time|to_jalali:'%H : %M : %S'}}</li>
                                        <li><i class="fa fa-calendar"></i>{{article.created_time|to_jalali:'%Y/%m/%d'}}</li>
                                    </ul>
                                    <span>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star-half-o"></i>
                                    </span>
                                </div>
                                <a href="{% url "blog_module:blog_detail_page" slug=article.slug %}">

                                    {% thumbnail article.image "862x398" padding=True  as im %}
                                        <img src="{{im.url}}" alt="">
                                    {% endthumbnail %}
                                </a>
                                <p>{{article.short_description}}</p>
                                <a class="btn btn-primary" href="{% url "blog_module:blog_detail_page" slug=article.slug %}">ادامـه مطلب</a>
                            </div>
                        {% empty %}
                        <h3 class="text-info text-center fa-border">NOT FOUND</h3>
                        {% endfor %}
						<div class="pagination-area">
							<ul class="pagination">

                                {% if page_obj.has_previous %}
                                    <li><a href="?page=1">First</a></li>
                                    <li><a href="?page={{page_obj.previous_page_number}}" class="fa fa-angle-double-left"></a></li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    <li><a href="?page={{page}}"
                                        class={% if page == page_obj.number %}"active"{% endif %}>
                                        {{page}}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
                                <li>
                                    <a href="?page={{page_obj.next_page_number}}" class="fa fa-angle-double-right"></a>
                                </li>
                                <li><a href="?page={{page_obj.paginator.num_pages}}" >Last</a></li>
                                {% endif %}

							</ul>
						</div>
					</div>
				</div>
				
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>دسته بندی مقالات</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
                                {% for category in categories %}
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordian" href="#{{category.id}}">
                                                {% if category.category_set.all %}
                                                    <span class="badge pull-right">
                                                        <i class="fa fa-plus"></i>
                                                    </span>
                                                    {{category}}
                                                {% else %}
                                                    <span class="badge pull-right">
                                                        <i class="fa fa-minus"></i>
                                                    </span>
                                                    {{category}}
                                                {% endif %}
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="{{category.id}}" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <ul>
                                                {% for sub_category in category.category_set.all %}
                                                    {% if sub_category.is_active %}
                                                        <li>
                                                            <a href="{% url "blog_module:blog_list_page" category_id=sub_category.id %}">{{sub_category}}
                                                            </a>
                                                        </li>
                                                    {% endif %}
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                {% empty %}EMPTY{% endfor %}

							<div class="panel panel-default">
								<div class="panel-heading">
                                    {% for article in articles %}
									    <h4 class="panel-title">
                                        <a href="{% url "blog_module:blog_detail_page" slug=article.slug %}">
                                        {{article.title}}
                                        </a>
                                        </h4>
                                    {% endfor %}
								</div>
							</div>

						</div><!--/category-productsr-->
					
						<div class="brands_products"><!--brands_products-->
							<h2>برنـد ها</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href=""> <span class="pull-left">(50)</span>برنـد 1</a></li>
									<li><a href=""> <span class="pull-left">(56)</span>برنـد 2</a></li>
									<li><a href=""> <span class="pull-left">(27)</span>برنـد 3</a></li>
									<li><a href=""> <span class="pull-left">(32)</span>برنـد 4</a></li>
									<li><a href=""> <span class="pull-left">(5)</span>برنـد 5</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->
						
						
						<div class="shipping text-center" style="background: white;"><!--shipping-->
							{% for banner in banners %}
                                <a href="{{banner.url}}" target="_blank">
                                    {% thumbnail banner.image "270x700" as im %}
                                        <img src="{{im.url}}" alt="">
                                    {% endthumbnail %}
                                </a>
                            {% endfor %}
						</div><!--/shipping-->
						
					</div>
				</div>
				
			</div>
		</div>
	</section>
{% endblock content %}