account_module/urls.py
from django.urls import path
from . import views


app_name = "account_module"
urlpatterns = [
    path('user-panel-dashboard/', views.UserPanelDashboardView.as_view(), name="user_panel_dashboard_page"),
    path('edit-user-profile/', views.EditUserProfileView.as_view(), name="edit_user_profile_page"),
    path('register/', views.RegisterView.as_view(), name="register_page"),
    path('active-account/<str:active_code>/', views.ActiveAccountView.as_view(), name="active_account_page"),
    path('login/', views.LoginView.as_view(), name="login_page"),
    path('logout/', views.LogoutView.as_view(), name="logout_page"),
    path('forget-pass/', views.ForgetPasswordView.as_view(), name="forget_pass_page"),
    path('change-pass/', views.ChangePasswordView.as_view(), name="change_pass_page"),
    path('reset-pass/<str:pass_ok>/', views.ResetPasswordView.as_view(), name="reset_pass_page"),
]

blog_module/urls.py
from django.urls import path
from . import views

app_name = 'blog_module'
urlpatterns = [
    path("", views.BlogListView.as_view(), name="blog_list_page"),
    path("<int:category_id>/", views.BlogListView.as_view(), name="blog_list_page"),
#     path('main/category/<int:category_id>/', get_list_by_category, name="category_page"),
#     path('main/author/<int:author_id>/', get_list_by_author, name="author_page"),
    path("detail/<slug:slug>/", views.BlogDetailView.as_view(), name="blog_detail_page"),
    path("submit-comment/", views.submit_comment, name="submit_comment"),
#     path("update/<int:article_id>/", update_page, name="update_page"),
#     path("delete/<int:article_id>/", delete_page, name="delete_page"),
#     path("article/", add_article, name="add_article"),
#     path("person/", add_person, name="add_person"),
    
    # path("update/<int:pk>/", update_page, name="update_page"),
]

eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home_module.urls')),
    path('accounts/', include("account_module.urls")),
    path('blog/', include("blog_module.urls")),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('order/', include('order_module.urls')),
    path('payment/', include('payment_module.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/forget-email.html
<h1>Hello {{user}}</h1>
<br>
<hr>
<br>
<h5>press this link to active your account.</h5>
<br><hr><br>
<a href="http://127.0.0.1:8000{% url "account_module:reset_pass_page" pass_ok=user.active_code %}">Click Me</a>
<br><hr><br>
<h6>Tanks</h6>

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "product_module/product.css" %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/new-email.html
<h1>Hello {{user}}</h1>
<br>
<hr>
<br>
<h5>press this link to active your account.</h5>
<br><hr><br>
<a href="http://127.0.0.1:8000{% url "account_module:active_account_page" active_code=user.active_code %}">Click Me</a>
<br><hr><br>
<h6>Tanks</h6>